//  MXFlutterFramework
//  Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.
//  Use of this source code is governed by a BSD-style license that can be
//  found in the LICENSE file.

import 'package:mxflutter/src/mirror/mx_mirror.dart';
import 'package:flutter/src/material/raised_button.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/src/material/button.dart';
import 'package:flutter/src/material/button_theme.dart';
import 'package:flutter/src/material/material_button.dart';
import 'package:flutter/src/material/theme.dart';
import 'package:flutter/src/material/theme_data.dart';

///把自己能处理的类注册到分发器中
Map<String, MXFunctionInvoke> registerRaisedButtonSeries() {
  var m = <String, MXFunctionInvoke>{};
  m[_raisedButton.funName] = _raisedButton;
  m[_raisedButtonIcon.funName] = _raisedButtonIcon;
  return m;
}

var _raisedButton = MXFunctionInvoke(
  "RaisedButton",
  ({
    Key key,
    dynamic onPressed,
    dynamic onLongPress,
    dynamic onHighlightChanged,
    MouseCursor mouseCursor,
    ButtonTextTheme textTheme,
    Color textColor,
    Color disabledTextColor,
    Color color,
    Color disabledColor,
    Color focusColor,
    Color hoverColor,
    Color highlightColor,
    Color splashColor,
    Brightness colorBrightness,
    dynamic elevation,
    dynamic focusElevation,
    dynamic hoverElevation,
    dynamic highlightElevation,
    dynamic disabledElevation,
    EdgeInsetsGeometry padding,
    VisualDensity visualDensity,
    ShapeBorder shape,
    Clip clipBehavior = Clip.none,
    FocusNode focusNode,
    bool autofocus = false,
    MaterialTapTargetSize materialTapTargetSize,
    Duration animationDuration,
    Widget child,
  }) =>
      RaisedButton(
    key: key,
    onPressed: createVoidCallbackClosure(_raisedButton.buildOwner, onPressed),
    onLongPress: createVoidCallbackClosure(_raisedButton.buildOwner, onLongPress),
    onHighlightChanged: createValueChangedGenericClosure<bool>(_raisedButton.buildOwner, onHighlightChanged),
    mouseCursor: mouseCursor,
    textTheme: textTheme,
    textColor: textColor,
    disabledTextColor: disabledTextColor,
    color: color,
    disabledColor: disabledColor,
    focusColor: focusColor,
    hoverColor: hoverColor,
    highlightColor: highlightColor,
    splashColor: splashColor,
    colorBrightness: colorBrightness,
    elevation: elevation?.toDouble(),
    focusElevation: focusElevation?.toDouble(),
    hoverElevation: hoverElevation?.toDouble(),
    highlightElevation: highlightElevation?.toDouble(),
    disabledElevation: disabledElevation?.toDouble(),
    padding: padding,
    visualDensity: visualDensity,
    shape: shape,
    clipBehavior: clipBehavior,
    focusNode: focusNode,
    autofocus: autofocus,
    materialTapTargetSize: materialTapTargetSize,
    animationDuration: animationDuration,
    child: child,
  ),
  [
    "key",
    "onPressed",
    "onLongPress",
    "onHighlightChanged",
    "mouseCursor",
    "textTheme",
    "textColor",
    "disabledTextColor",
    "color",
    "disabledColor",
    "focusColor",
    "hoverColor",
    "highlightColor",
    "splashColor",
    "colorBrightness",
    "elevation",
    "focusElevation",
    "hoverElevation",
    "highlightElevation",
    "disabledElevation",
    "padding",
    "visualDensity",
    "shape",
    "clipBehavior",
    "focusNode",
    "autofocus",
    "materialTapTargetSize",
    "animationDuration",
    "child",
  ],
);
var _raisedButtonIcon = MXFunctionInvoke(
  "RaisedButton.icon",
  ({
    Key key,
    dynamic onPressed,
    dynamic onLongPress,
    dynamic onHighlightChanged,
    MouseCursor mouseCursor,
    ButtonTextTheme textTheme,
    Color textColor,
    Color disabledTextColor,
    Color color,
    Color disabledColor,
    Color focusColor,
    Color hoverColor,
    Color highlightColor,
    Color splashColor,
    Brightness colorBrightness,
    dynamic elevation,
    dynamic highlightElevation,
    dynamic disabledElevation,
    ShapeBorder shape,
    // MX Modified begin
    Clip clipBehavior = Clip.none,
    // MX Modified end
    FocusNode focusNode,
    // MX Modified begin
    bool autofocus = false,
    // MX Modified end
    EdgeInsetsGeometry padding,
    MaterialTapTargetSize materialTapTargetSize,
    Duration animationDuration,
    Widget icon,
    Widget label,
  }) =>
      RaisedButton.icon(
    key: key,
    onPressed: createVoidCallbackClosure(_raisedButtonIcon.buildOwner, onPressed),
    onLongPress: createVoidCallbackClosure(_raisedButtonIcon.buildOwner, onLongPress),
    onHighlightChanged: createValueChangedGenericClosure<bool>(_raisedButtonIcon.buildOwner, onHighlightChanged),
    mouseCursor: mouseCursor,
    textTheme: textTheme,
    textColor: textColor,
    disabledTextColor: disabledTextColor,
    color: color,
    disabledColor: disabledColor,
    focusColor: focusColor,
    hoverColor: hoverColor,
    highlightColor: highlightColor,
    splashColor: splashColor,
    colorBrightness: colorBrightness,
    elevation: elevation?.toDouble(),
    highlightElevation: highlightElevation?.toDouble(),
    disabledElevation: disabledElevation?.toDouble(),
    shape: shape,
    clipBehavior: clipBehavior,
    focusNode: focusNode,
    autofocus: autofocus,
    padding: padding,
    materialTapTargetSize: materialTapTargetSize,
    animationDuration: animationDuration,
    icon: icon,
    label: label,
  ),
  [
    "key",
    "onPressed",
    "onLongPress",
    "onHighlightChanged",
    "mouseCursor",
    "textTheme",
    "textColor",
    "disabledTextColor",
    "color",
    "disabledColor",
    "focusColor",
    "hoverColor",
    "highlightColor",
    "splashColor",
    "colorBrightness",
    "elevation",
    "highlightElevation",
    "disabledElevation",
    "shape",
    "clipBehavior",
    "focusNode",
    "autofocus",
    "padding",
    "materialTapTargetSize",
    "animationDuration",
    "icon",
    "label",
  ],
);
