//  MXFlutterFramework
//  Copyright 2019 The MXFlutter Authors. All rights reserved.
//
//  Use of this source code is governed by a MIT-style license that can be
//  found in the LICENSE file.

import 'package:mxflutter/src/mirror/mx_mirror.dart';
import 'package:flutter/material.dart';
import 'src/material/about.dart';
import 'src/material/animated_icons.dart';
import 'src/material/app.dart';
import 'src/material/icon_button.dart';
import 'src/material/arc.dart';
import 'src/material/banner.dart';
import 'src/material/bottom_app_bar.dart';
import 'src/material/bottom_navigation_bar.dart';
import 'src/material/bottom_sheet_theme.dart';
import 'src/material/card.dart';
import 'src/material/checkbox.dart';
import 'src/material/checkbox_list_tile.dart';
import 'src/material/chip.dart';
import 'src/material/circle_avatar.dart';
import 'src/material/colors.dart';
import 'src/material/constants.dart';
import 'src/material/data_table.dart';
import 'src/material/data_table_source.dart';
import 'src/material/drawer_header.dart';
import 'src/material/dropdown.dart';
import 'src/material/expand_icon.dart';
import 'src/material/expansion_panel.dart';
import 'src/material/expansion_tile.dart';
import 'src/material/floating_action_button_theme.dart';
import 'src/material/flutter_logo.dart';
import 'src/material/grid_tile.dart';
import 'src/material/grid_tile_bar.dart';
import 'src/material/icons.dart';
import 'src/material/ink_decoration.dart';
import 'src/material/ink_ripple.dart';
import 'src/material/input_border.dart';
import 'src/material/material_state.dart';
import 'src/material/mergeable_material.dart';
import 'src/material/page.dart';
import 'src/material/paginated_data_table.dart';
import 'src/material/pickers/pickers.dart';
import 'src/material/popup_menu.dart';
import 'src/material/progress_indicator.dart';
import 'src/material/radio.dart';
import 'src/material/radio_list_tile.dart';
import 'src/material/range_slider.dart';
import 'src/material/refresh_indicator.dart';
import 'src/material/scrollbar.dart';
import 'src/material/search.dart';
import 'src/material/selectable_text.dart';
import 'src/material/shadows.dart';
import 'src/material/slider.dart';
import 'src/material/stepper.dart';
import 'src/material/switch.dart';
import 'src/material/switch_list_tile.dart';
import 'src/material/tab_controller.dart';
import 'src/material/tab_indicator.dart';
import 'src/material/text_field.dart';
import 'src/material/text_form_field.dart';
import 'src/material/text_selection.dart';
import 'src/material/typography.dart';
import 'src/material/time_picker.dart';
import 'src/material/toggle_buttons.dart';
import 'src/material/toggleable.dart';
import 'src/material/user_accounts_drawer_header.dart';
import 'src/material/curves.dart';
import 'src/material/pickers/calendar_date_picker.dart';
import 'src/material/pickers/date_picker_common.dart';
import 'src/material/pickers/date_picker_deprecated.dart';
import 'src/material/pickers/date_picker_dialog.dart';
import 'src/material/pickers/input_date_picker.dart';
import 'src/material/pickers/date_utils.dart';
import 'src/material/pickers/date_picker_header.dart';


class MXProxyMaterial {
  static Map<String, MXFunctionInvoke> registerSeries() {
    Map<String, MXFunctionInvoke> m = {};
    m.addAll(MXProxyAbout.registerSeries());
    m.addAll(MXProxyAnimatedIcons.registerSeries());
    m.addAll(MXProxyApp.registerSeries());
    m.addAll(MXProxyIconButton.registerSeries());
    m.addAll(MXProxyArc.registerSeries());
    m.addAll(MXProxyBanner.registerSeries());
    m.addAll(MXProxyBottomAppBar.registerSeries());
    m.addAll(MXProxyBottomNavigationBar.registerSeries());
    m.addAll(MXProxyBottomSheetTheme.registerSeries());
    m.addAll(MXProxyCard.registerSeries());
    m.addAll(MXProxyCheckbox.registerSeries());
    m.addAll(MXProxyCheckboxListTile.registerSeries());
    m.addAll(MXProxyChip.registerSeries());
    m.addAll(MXProxyCircleAvatar.registerSeries());
    m.addAll(MXProxyColors.registerSeries());
    m.addAll(MXProxyConstants.registerSeries());
    m.addAll(MXProxyDataTable.registerSeries());
    m.addAll(MXProxyDataTableSource.registerSeries());
    m.addAll(MXProxyDrawerHeader.registerSeries());
    m.addAll(MXProxyDropdown.registerSeries());
    m.addAll(MXProxyExpandIcon.registerSeries());
    m.addAll(MXProxyExpansionPanel.registerSeries());
    m.addAll(MXProxyExpansionTile.registerSeries());
    m.addAll(MXProxyFloatingActionButtonTheme.registerSeries());
    m.addAll(MXProxyFlutterLogo.registerSeries());
    m.addAll(MXProxyGridTile.registerSeries());
    m.addAll(MXProxyGridTileBar.registerSeries());
    m.addAll(MXProxyIcons.registerSeries());
    m.addAll(MXProxyInkDecoration.registerSeries());
    m.addAll(MXProxyInkRipple.registerSeries());
    m.addAll(MXProxyInputBorder.registerSeries());
    m.addAll(MXProxyMaterialState.registerSeries());
    m.addAll(MXProxyMergeableMaterial.registerSeries());
    m.addAll(MXProxyPage.registerSeries());
    m.addAll(MXProxyPaginatedDataTable.registerSeries());
    m.addAll(MXProxyPickers.registerSeries());
    m.addAll(MXProxyPopupMenu.registerSeries());
    m.addAll(MXProxyProgressIndicator.registerSeries());
    m.addAll(MXProxyRadio.registerSeries());
    m.addAll(MXProxyRadioListTile.registerSeries());
    m.addAll(MXProxyRangeSlider.registerSeries());
    m.addAll(MXProxyRefreshIndicator.registerSeries());
    m.addAll(MXProxyScrollbar.registerSeries());
    m.addAll(MXProxySearch.registerSeries());
    m.addAll(MXProxySelectableText.registerSeries());
    m.addAll(MXProxyShadows.registerSeries());
    m.addAll(MXProxySlider.registerSeries());
    m.addAll(MXProxyStepper.registerSeries());
    m.addAll(MXProxySwitch.registerSeries());
    m.addAll(MXProxySwitchListTile.registerSeries());
    m.addAll(MXProxyTabController.registerSeries());
    m.addAll(MXProxyTabIndicator.registerSeries());
    m.addAll(MXProxyTextField.registerSeries());
    m.addAll(MXProxyTextFormField.registerSeries());
    m.addAll(MXProxyTextSelection.registerSeries());
    m.addAll(MXProxyTypography.registerSeries());
    m.addAll(MXProxyTimePicker.registerSeries());
    m.addAll(MXProxyToggleButtons.registerSeries());
    m.addAll(MXProxyToggleable.registerSeries());
    m.addAll(MXProxyUserAccountsDrawerHeader.registerSeries());
    m.addAll(MXProxyCurves.registerSeries());
    m.addAll(MXProxyCalendarDatePicker.registerSeries());
    m.addAll(MXProxyDatePickerCommon.registerSeries());
    m.addAll(MXProxyDatePickerDeprecated.registerSeries());
    m.addAll(MXProxyDatePickerDialog.registerSeries());
    m.addAll(MXProxyInputDatePicker.registerSeries());
    m.addAll(MXProxyDateUtils.registerSeries());
    m.addAll(MXProxyDatePickerHeader.registerSeries());
    return m;
  }
}
