//  MXFlutterFramework
//  Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.
//  Use of this source code is governed by a BSD-style license that can be
//  found in the LICENSE file.

import 'package:mxflutter/src/mirror/mx_mirror.dart';
import './src/material/about.dart';
import './src/material/animated_icons.dart';
import './src/material/app.dart';
import './src/material/app_bar.dart';
import './src/material/app_bar_theme.dart';
import './src/material/arc.dart';
import './src/material/back_button.dart';
import './src/material/banner.dart';
import './src/material/banner_theme.dart';
import './src/material/bottom_app_bar.dart';
import './src/material/bottom_app_bar_theme.dart';
import './src/material/bottom_navigation_bar.dart';
import './src/material/bottom_navigation_bar_theme.dart';
import './src/material/bottom_sheet.dart';
import './src/material/bottom_sheet_theme.dart';
import './src/material/button.dart';
import './src/material/button_bar.dart';
import './src/material/button_bar_theme.dart';
import './src/material/button_theme.dart';
import './src/material/card.dart';
import './src/material/card_theme.dart';
import './src/material/checkbox.dart';
import './src/material/checkbox_list_tile.dart';
import './src/material/chip.dart';
import './src/material/chip_theme.dart';
import './src/material/circle_avatar.dart';
import './src/material/color_scheme.dart';
import './src/material/colors.dart';
import './src/material/constants.dart';
import './src/material/data_table.dart';
import './src/material/data_table_source.dart';
import './src/material/debug.dart';
import './src/material/dialog.dart';
import './src/material/dialog_theme.dart';
import './src/material/divider.dart';
import './src/material/divider_theme.dart';
import './src/material/drawer.dart';
import './src/material/drawer_header.dart';
import './src/material/dropdown.dart';
import './src/material/elevation_overlay.dart';
import './src/material/expand_icon.dart';
import './src/material/expansion_panel.dart';
import './src/material/expansion_tile.dart';
import './src/material/feedback.dart';
import './src/material/flat_button.dart';
import './src/material/flexible_space_bar.dart';
import './src/material/floating_action_button.dart';
import './src/material/floating_action_button_location.dart';
import './src/material/floating_action_button_theme.dart';
import './src/material/flutter_logo.dart';
import './src/material/grid_tile.dart';
import './src/material/grid_tile_bar.dart';
import './src/material/icon_button.dart';
import './src/material/icons.dart';
import './src/material/ink_decoration.dart';
import './src/material/ink_highlight.dart';
import './src/material/ink_ripple.dart';
import './src/material/ink_splash.dart';
import './src/material/ink_well.dart';
import './src/material/input_border.dart';
import './src/material/input_decorator.dart';
import './src/material/list_tile.dart';
import './src/material/material.dart';
import './src/material/material_button.dart';
import './src/material/material_localizations.dart';
import './src/material/material_state.dart';
import './src/material/mergeable_material.dart';
import './src/material/navigation_rail.dart';
import './src/material/navigation_rail_theme.dart';
import './src/material/outline_button.dart';
import './src/material/page.dart';
import './src/material/page_transitions_theme.dart';
import './src/material/paginated_data_table.dart';
import './src/material/pickers/pickers.dart';
import './src/material/popup_menu.dart';
import './src/material/popup_menu_theme.dart';
import './src/material/progress_indicator.dart';
import './src/material/radio.dart';
import './src/material/radio_list_tile.dart';
import './src/material/raised_button.dart';
import './src/material/range_slider.dart';
import './src/material/refresh_indicator.dart';
import './src/material/reorderable_list.dart';
import './src/material/scaffold.dart';
import './src/material/scrollbar.dart';
import './src/material/search.dart';
import './src/material/selectable_text.dart';
import './src/material/shadows.dart';
import './src/material/slider.dart';
import './src/material/slider_theme.dart';
import './src/material/snack_bar.dart';
import './src/material/snack_bar_theme.dart';
import './src/material/stepper.dart';
import './src/material/switch.dart';
import './src/material/switch_list_tile.dart';
import './src/material/tab_bar_theme.dart';
import './src/material/tab_controller.dart';
import './src/material/tab_indicator.dart';
import './src/material/tabs.dart';
import './src/material/text_field.dart';
import './src/material/text_form_field.dart';
import './src/material/text_selection.dart';
import './src/material/text_theme.dart';
import './src/material/theme.dart';
import './src/material/theme_data.dart';
import './src/material/time.dart';
import './src/material/time_picker.dart';
import './src/material/time_picker_theme.dart';
import './src/material/toggle_buttons.dart';
import './src/material/toggle_buttons_theme.dart';
import './src/material/toggleable.dart';
import './src/material/tooltip.dart';
import './src/material/tooltip_theme.dart';
import './src/material/typography.dart';
import './src/material/user_accounts_drawer_header.dart';
import './src/material/curves.dart';
import './src/material/pickers/calendar_date_picker.dart';
import './src/material/pickers/date_picker_common.dart';
import './src/material/pickers/date_picker_deprecated.dart';
import './src/material/pickers/date_picker_dialog.dart';
import './src/material/pickers/date_range_picker_dialog.dart';
import './src/material/pickers/input_date_picker.dart';
import './src/material/pickers/date_utils.dart';
import './src/material/pickers/date_picker_header.dart';
import './src/material/pickers/calendar_date_range_picker.dart';
import './src/material/pickers/input_date_range_picker.dart';

Map<String, MXFunctionInvoke> registerMaterialLibrarySeries() {
  Map<String, MXFunctionInvoke> m = {};
  m.addAll(registerAboutSeries());
  m.addAll(registerAnimatedIconsSeries());
  m.addAll(registerAppSeries());
  m.addAll(registerAppBarSeries());
  m.addAll(registerAppBarThemeSeries());
  m.addAll(registerArcSeries());
  m.addAll(registerBackButtonSeries());
  m.addAll(registerBannerSeries());
  m.addAll(registerBannerThemeSeries());
  m.addAll(registerBottomAppBarSeries());
  m.addAll(registerBottomAppBarThemeSeries());
  m.addAll(registerBottomNavigationBarSeries());
  m.addAll(registerBottomNavigationBarThemeSeries());
  m.addAll(registerBottomSheetSeries());
  m.addAll(registerBottomSheetThemeSeries());
  m.addAll(registerButtonSeries());
  m.addAll(registerButtonBarSeries());
  m.addAll(registerButtonBarThemeSeries());
  m.addAll(registerButtonThemeSeries());
  m.addAll(registerCardSeries());
  m.addAll(registerCardThemeSeries());
  m.addAll(registerCheckboxSeries());
  m.addAll(registerCheckboxListTileSeries());
  m.addAll(registerChipSeries());
  m.addAll(registerChipThemeSeries());
  m.addAll(registerCircleAvatarSeries());
  m.addAll(registerColorSchemeSeries());
  m.addAll(registerColorsSeries());
  m.addAll(registerConstantsSeries());
  m.addAll(registerDataTableSeries());
  m.addAll(registerDataTableSourceSeries());
  m.addAll(registerDebugSeries());
  m.addAll(registerDialogSeries());
  m.addAll(registerDialogThemeSeries());
  m.addAll(registerDividerSeries());
  m.addAll(registerDividerThemeSeries());
  m.addAll(registerDrawerSeries());
  m.addAll(registerDrawerHeaderSeries());
  m.addAll(registerDropdownSeries());
  m.addAll(registerElevationOverlaySeries());
  m.addAll(registerExpandIconSeries());
  m.addAll(registerExpansionPanelSeries());
  m.addAll(registerExpansionTileSeries());
  m.addAll(registerFeedbackSeries());
  m.addAll(registerFlatButtonSeries());
  m.addAll(registerFlexibleSpaceBarSeries());
  m.addAll(registerFloatingActionButtonSeries());
  m.addAll(registerFloatingActionButtonLocationSeries());
  m.addAll(registerFloatingActionButtonThemeSeries());
  m.addAll(registerFlutterLogoSeries());
  m.addAll(registerGridTileSeries());
  m.addAll(registerGridTileBarSeries());
  m.addAll(registerIconButtonSeries());
  m.addAll(registerIconsSeries());
  m.addAll(registerInkDecorationSeries());
  m.addAll(registerInkHighlightSeries());
  m.addAll(registerInkRippleSeries());
  m.addAll(registerInkSplashSeries());
  m.addAll(registerInkWellSeries());
  m.addAll(registerInputBorderSeries());
  m.addAll(registerInputDecoratorSeries());
  m.addAll(registerListTileSeries());
  m.addAll(registerMaterialSeries());
  m.addAll(registerMaterialButtonSeries());
  m.addAll(registerMaterialLocalizationsSeries());
  m.addAll(registerMaterialStateSeries());
  m.addAll(registerMergeableMaterialSeries());
  m.addAll(registerNavigationRailSeries());
  m.addAll(registerNavigationRailThemeSeries());
  m.addAll(registerOutlineButtonSeries());
  m.addAll(registerPageSeries());
  m.addAll(registerPageTransitionsThemeSeries());
  m.addAll(registerPaginatedDataTableSeries());
  m.addAll(registerPickersSeries());
  m.addAll(registerPopupMenuSeries());
  m.addAll(registerPopupMenuThemeSeries());
  m.addAll(registerProgressIndicatorSeries());
  m.addAll(registerRadioSeries());
  m.addAll(registerRadioListTileSeries());
  m.addAll(registerRaisedButtonSeries());
  m.addAll(registerRangeSliderSeries());
  m.addAll(registerRefreshIndicatorSeries());
  m.addAll(registerReorderableListSeries());
  m.addAll(registerScaffoldSeries());
  m.addAll(registerScrollbarSeries());
  m.addAll(registerSearchSeries());
  m.addAll(registerSelectableTextSeries());
  m.addAll(registerShadowsSeries());
  m.addAll(registerSliderSeries());
  m.addAll(registerSliderThemeSeries());
  m.addAll(registerSnackBarSeries());
  m.addAll(registerSnackBarThemeSeries());
  m.addAll(registerStepperSeries());
  m.addAll(registerSwitchSeries());
  m.addAll(registerSwitchListTileSeries());
  m.addAll(registerTabBarThemeSeries());
  m.addAll(registerTabControllerSeries());
  m.addAll(registerTabIndicatorSeries());
  m.addAll(registerTabsSeries());
  m.addAll(registerTextFieldSeries());
  m.addAll(registerTextFormFieldSeries());
  m.addAll(registerTextSelectionSeries());
  m.addAll(registerTextThemeSeries());
  m.addAll(registerThemeSeries());
  m.addAll(registerThemeDataSeries());
  m.addAll(registerTimeSeries());
  m.addAll(registerTimePickerSeries());
  m.addAll(registerTimePickerThemeSeries());
  m.addAll(registerToggleButtonsSeries());
  m.addAll(registerToggleButtonsThemeSeries());
  m.addAll(registerToggleableSeries());
  m.addAll(registerTooltipSeries());
  m.addAll(registerTooltipThemeSeries());
  m.addAll(registerTypographySeries());
  m.addAll(registerUserAccountsDrawerHeaderSeries());
  m.addAll(registerCurvesSeries());
  m.addAll(registerCalendarDatePickerSeries());
  m.addAll(registerDatePickerCommonSeries());
  m.addAll(registerDatePickerDeprecatedSeries());
  m.addAll(registerDatePickerDialogSeries());
  m.addAll(registerDateRangePickerDialogSeries());
  m.addAll(registerInputDatePickerSeries());
  m.addAll(registerDateUtilsSeries());
  m.addAll(registerDatePickerHeaderSeries());
  m.addAll(registerCalendarDateRangePickerSeries());
  m.addAll(registerInputDateRangePickerSeries());
  return m;
}
