//  MXFlutterFramework
//  Copyright 2019 The MXFlutter Authors. All rights reserved.
//
//  Use of this source code is governed by a MIT-style license that can be
//  found in the LICENSE file.

import 'package:mxflutter/src/mirror/mx_mirror.dart';
import 'src/widgets/widget_span.dart';
import 'src/widgets/animated_cross_fade.dart';
import 'src/widgets/animated_list.dart';
import 'src/widgets/animated_size.dart';
import 'src/widgets/animated_switcher.dart';
import 'src/widgets/annotated_region.dart';
import 'src/widgets/async.dart';
import 'src/widgets/bottom_navigation_bar_item.dart';
import 'src/widgets/color_filter.dart';
import 'src/widgets/dismissible.dart';
import 'src/widgets/drag_target.dart';
import 'src/widgets/draggable_scrollable_sheet.dart';
import 'src/widgets/fade_in_image.dart';
import 'src/widgets/form.dart';
import 'src/widgets/grid_paper.dart';
import 'src/widgets/heroes.dart';
import 'src/widgets/icon.dart';
import 'src/widgets/icon_data.dart';
import 'src/widgets/icon_theme.dart';
import 'src/widgets/icon_theme_data.dart';
import 'src/widgets/image_filter.dart';
import 'src/widgets/image_icon.dart';
import 'src/widgets/implicit_animations.dart';
import 'src/widgets/layout_builder.dart';
import 'src/widgets/list_wheel_scroll_view.dart';
import 'src/widgets/navigation_toolbar.dart';
import 'src/widgets/nested_scroll_view.dart';
import 'src/widgets/orientation_builder.dart';
import 'src/widgets/page_view.dart';
import 'src/widgets/placeholder.dart';
import 'src/widgets/platform_view.dart';
import 'src/widgets/preferred_size.dart';
import 'src/widgets/primary_scroll_controller.dart';
import 'src/widgets/raw_keyboard_listener.dart';
import 'src/widgets/safe_area.dart';
import 'src/widgets/scroll_metrics.dart';
import 'src/widgets/scroll_simulation.dart';
import 'src/widgets/scroll_view.dart';
import 'src/widgets/scrollbar.dart';
import 'src/widgets/single_child_scroll_view.dart';
import 'src/widgets/size_changed_layout_notifier.dart';
import 'src/widgets/sliver_fill.dart';
import 'src/widgets/sliver_layout_builder.dart';
import 'src/widgets/sliver_persistent_header.dart';
import 'src/widgets/sliver_prototype_extent_list.dart';
import 'src/widgets/spacer.dart';
import 'src/widgets/status_transitions.dart';
import 'src/widgets/texture.dart';
import 'src/widgets/tween_animation_builder.dart';
import 'src/widgets/unique_widget.dart';
import 'src/widgets/value_listenable_builder.dart';
import 'src/widgets/will_pop_scope.dart';
import 'src/widgets/constants.dart';
import 'src/widgets/route_notification_messages.dart';


Map<String, MXFunctionInvoke> registerWidgetsSeries() {
  Map<String, MXFunctionInvoke> m = {};
  m.addAll(registerWidgetSpanSeries());
  m.addAll(registerAnimatedCrossFadeSeries());
  m.addAll(registerAnimatedListSeries());
  m.addAll(registerAnimatedSizeSeries());
  m.addAll(registerAnimatedSwitcherSeries());
  m.addAll(registerAnnotatedRegionSeries());
  m.addAll(registerAsyncSeries());
  m.addAll(registerBottomNavigationBarItemSeries());
  m.addAll(registerColorFilterSeries());
  m.addAll(registerDismissibleSeries());
  m.addAll(registerDragTargetSeries());
  m.addAll(registerDraggableScrollableSheetSeries());
  m.addAll(registerFadeInImageSeries());
  m.addAll(registerFormSeries());
  m.addAll(registerGridPaperSeries());
  m.addAll(registerHeroesSeries());
  m.addAll(registerIconSeries());
  m.addAll(registerIconDataSeries());
  m.addAll(registerIconThemeSeries());
  m.addAll(registerIconThemeDataSeries());
  m.addAll(registerImageFilterSeries());
  m.addAll(registerImageIconSeries());
  m.addAll(registerImplicitAnimationsSeries());
  m.addAll(registerLayoutBuilderSeries());
  m.addAll(registerListWheelScrollViewSeries());
  m.addAll(registerNavigationToolbarSeries());
  m.addAll(registerNestedScrollViewSeries());
  m.addAll(registerOrientationBuilderSeries());
  m.addAll(registerPageViewSeries());
  m.addAll(registerPlaceholderSeries());
  m.addAll(registerPlatformViewSeries());
  m.addAll(registerPreferredSizeSeries());
  m.addAll(registerPrimaryScrollControllerSeries());
  m.addAll(registerRawKeyboardListenerSeries());
  m.addAll(registerSafeAreaSeries());
  m.addAll(registerScrollMetricsSeries());
  m.addAll(registerScrollSimulationSeries());
  m.addAll(registerScrollViewSeries());
  m.addAll(registerScrollbarSeries());
  m.addAll(registerSingleChildScrollViewSeries());
  m.addAll(registerSizeChangedLayoutNotifierSeries());
  m.addAll(registerSliverFillSeries());
  m.addAll(registerSliverLayoutBuilderSeries());
  m.addAll(registerSliverPersistentHeaderSeries());
  m.addAll(registerSliverPrototypeExtentListSeries());
  m.addAll(registerSpacerSeries());
  m.addAll(registerStatusTransitionsSeries());
  m.addAll(registerTextureSeries());
  m.addAll(registerTweenAnimationBuilderSeries());
  m.addAll(registerUniqueWidgetSeries());
  m.addAll(registerValueListenableBuilderSeries());
  m.addAll(registerWillPopScopeSeries());
  m.addAll(registerConstantsSeries());
  m.addAll(registerRouteNotificationMessagesSeries());
  return m;
}
